# setup
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "cjbassi/ytop"

tap "argon/mas"
tap "c-bata/kube-prompt"
tap "facebook/fb"
tap "heroku/brew"
tap "neovim/neovim"
tap "rcmdnk/file"
tap "sanemat/font"
tap "homebrew/cask-fonts"

brew "git"
brew "bash"
brew "ghq"

cask "karabiner-elements"
cask "slack"
cask "alfred"
cask "clipy"

brew "bash-completion"
brew "asdf"

brew "mas"

mas "1Password 7", id: 1333542190

cask "docker"
cask "iterm2"
brew "tmux"
cask "alacritty"
cask "hyper"
brew "tig"
brew "fzf"

cask "hyperswitch"

brew "memcached"
brew "mysql@5.7", link: true
brew "redis"

brew "coreutils"
brew "automake"
brew "autoconf"
brew "openssl"
brew "libyaml"
brew "libxslt"
brew "libtool"
brew "unixodbc"
brew "unzip"

brew "readline", link: true
brew "cmake"
brew "crf++"
brew "freetype"
brew "gettext"
brew "gawk"
brew "gdb"
brew "gnupg"
brew "ideviceinstaller"
brew "imagemagick@6"
brew "ios-deploy"
brew "jq"
brew "lua"
brew "luajit"
brew "nmap"
brew "pkg-config"
brew "reattach-to-user-namespace"
brew "rename"
brew "translate-shell"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "z"
brew "heroku/brew/heroku"
brew "rcmdnk/file/brew-file"
brew "sanemat/font/ricty"
brew "fontforge"
cask "react-native-debugger"

cask "gitify"
cask "gyazo"
cask "cheatsheet"
cask "kap"
brew "neovim", args: ["HEAD"]
brew "osquery"
brew "diff-so-fancy"
brew "curl"

cask "android-studio"
cask "android-sdk"
cask "sublime-text"
cask "dash"
cask "ngrok"

cask "bettertouchtool"
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694

# Email
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835

brew "ctags"
cask 'font-hack-nerd-font'

# 各種便利コマンド系
brew 'bat'
brew 'exa'
brew 'fd'
brew 'ripgrep'
brew 'procs'
brew 'hyperfine'
brew 'ytop'
brew 'bandwhich'
